# Generated by Django 3.0.7 on 2020-06-24 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.TextField()),
                ('technology', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
