# Generated by Django 3.0.7 on 2020-10-12 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
